// lib/services/state_mappings.dart
// Keys should match the normalized state name saved in your profile (lowercase).
const Map<String, String> STATE_LISTING_MAP = {
  // default / main (not strictly required)
  'default': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=',

  'andaman and nicobar islands': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=1',
  'andhra pradesh': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=5',
  'arunachal pradesh': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=19',
  'assam': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=37',
  'bihar': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=65',
  'chandigarh': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=104',
  'chhattisgarh': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=106',
  // common misspelling
  'chattisgarh': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=106',
  'dadra and nagar haveli': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=134',
  'delhi': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=139',
  'goa': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=151',
  'gujarat': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=154',
  'haryana': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=188',
  'himachal pradesh': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=210',
  'jammu and kashmir': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=223',
  'jharkhand': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=246',
  'karnataka': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=271',
  'kerala': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=302',
  'ladakh': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=712',
  'lakshadweep': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=317',
  'madhya pradesh': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=319',
  'maharashtra': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=371',
  'manipur': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=408',
  'meghalaya': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=418',
  'mizoram': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=430',
  'nagaland': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=439',
  'odisha': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=451',
  'puducherry': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=482',
  'punjab': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=487',
  'rajasthan': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=510',
  'sikkim': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=544',
  'tamil nadu': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=549',
  'telangana': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=582',
  'tripura': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=593',
  'uttar pradesh': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=602',
  'uttarakhand': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=678',
  'west bengal': 'https://services.india.gov.in/service/search?kw=&ln=en&cat_id_search=98&location=district&state_id=692',
};
